# Generated by Django 4.2.30 on 2026-04-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('inn', models.IntegerField()),
                ('legal_address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fio', models.CharField(max_length=100)),
                ('passport_series', models.IntegerField()),
                ('passport_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotrydnik.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sotrydnik.position')),
            ],
        ),
    ]
