# Generated by Django 4.2.30 on 2026-04-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotrydnik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
    ]
