# Generated by Django 4.2.30 on 2026-04-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sotrydnik', '0002_rename_company_name_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='company_name',
            new_name='company',
        ),
    ]
